### ISSUE TITLE
Responsive Design: Positioning of texts

### ISSUE THREAD

**Issue by alfert** [carbonara-coinpensator/carbonara-frontend#13]
The layout must allow for small and portrait screens, as for mobiles. Currently, various text boxes overlap in such cases and are unreadable. 

(detail for #7)

**Comment by kats4** [comment]
**Example:**
First Viewport
The direct top link to the "Calculator" is cut in half and illegible.
![Top_Link](https://user-images.githubusercontent.com/50578542/57618061-ae2e9f00-7582-11e9-9184-e641ff6417c6.PNG)

**Comment by kats4** [comment]
On iPhone
Positioning of the long labels of buttons inside the interaction box not ideal.
Distance of second to first line too big, copy disintegrates and is read as separate items.
![distance_lines](https://user-images.githubusercontent.com/50578542/57619624-9ce79180-7586-11e9-9ce7-12fd2919c56f.png)

**Comment by kats4** [comment]
iPhone
CO2 Graph: The labels for the graph and the numbers of the scale are cut off or overlapping
![labels_graph](https://user-images.githubusercontent.com/50578542/57620223-70347980-7588-11e9-92fc-06c71d44d332.png)

**Comment by kats4** [comment]
iPhone
Example data at the calculator overlaps
Perhaps position below each other...?
![overlapping_data](https://user-images.githubusercontent.com/50578542/57621402-a0314c00-758b-11e9-9a77-479f78431f2e.png)

**Comment by kats4** [comment]
Mobile iPhone
Compensation results: the columns overlap each other and are hard to read.
![results](https://user-images.githubusercontent.com/50578542/57622543-277fbf00-758e-11e9-9b17-5df90816223f.png)

**Comment by kats4** [comment]
Mobile iPhone
Short version of results: Text is overlapping
![short version overlap](https://user-images.githubusercontent.com/50578542/57622878-d3c1a580-758e-11e9-948b-73538e5c8dd1.png)

**Comment by kats4** [comment]
Everything above has been done by Jan except for the last part: Sticky results element.
