### ISSUE TITLE
Responsive Design: CO2 Graph

### ISSUE THREAD

**Issue by alfert** [carbonara-coinpensator/carbonara-frontend#14]
Details for #7 

- [ ] The hover functionality in the C02 graph cannot work with a touch user interface
- [ ] The zoom back function does not work yet

**Comment by kats4** [comment]
Optimize the CO2 graph for mobile
- reduced preview only on longscroller (no labels, no numbers, no icons, only graphs bigger and year)
- on tap (on e.g. "plus" or "magnifier") graph opens fullscreen in landscape mode
- landscape mode: with labels, numbers and both interaction icons
- Interactions landscape mode: tap=hover informations from desktop?
- Interactions landscape mode: two fingers pinch=zoom in on graph section
- Interactions landscape mode: tap on home=reset of zoom
![landscape via plus](https://user-images.githubusercontent.com/50578542/57620713-e1c0f780-7589-11e9-88ee-3a2ba5d67ab3.png)

**Comment by kats4** [comment]
Optimize Toggle between BTC price and Energy consumption graph
Position next to each other for better usability
To be discussed: functionality perhaps only in landscape mode? 
![toggle_position](https://user-images.githubusercontent.com/50578542/57620929-7297d300-758a-11e9-8076-ab4083df6110.png)

**Comment by kats4** [comment]
Desktop
**Make interaction icons BIGGER**
The icons to zoom in and to reset the zoom on the graph are rather small. 
Idea: Make them bigger, find a more prominent position for them?
Also: in the hover state, a tooltip appears. Here we could add a few more words to make the interaction clearer to the user.
e.g. Magnifier: Select a section to zoom in
Home: Reset zoom (ok)
![Icons-Graph](https://user-images.githubusercontent.com/50578542/57693485-9a9a3b80-7649-11e9-9326-b539763f3a13.png)
![Tooltip](https://user-images.githubusercontent.com/50578542/57693490-a0901c80-7649-11e9-9507-69f8ef7988da.png)

**Comment by OleGiebel** [comment]
> **Optimize Toggle between BTC price and Energy consumption graph**
> Position next to each other for better usability
> To be discussed: functionality perhaps only in landscape mode?
Arranging the bubbles next to each other in the legend works. Some color suggestions fto better differentiate between them (Dark green vs black)?

**Comment by kats4** [comment]
@OleGiebel How about RED or ORANGE for the Energy? And black or dark green for the Bitcoin?
