### ISSUE TITLE
World Map: Sliders for mining pools overlap sometimes

### ISSUE THREAD

**Issue by alfert** [carbonara-coinpensator/carbonara-frontend#15]
Details for #7 

- [x] Sliders for the mining pools overlap sometimes
- [x] Slides are sorted per alphabet and instead of east-west position on the map. This makes it difficult to find the proper slider. 
- [ ] A reset button for the sliders and the year of the transaction would be nice
- [x] Refreshing of the year slides does not always work properly, when setting to the boundaries 
- [ ] Setting the pool-sliders to a specific setting is tedious, because the change in one pool implies changes in the neighbour pool as well.

**Comment by kats4** [comment]
Mobile iPhone
To be discussed: Are sliders the best interaction elements on mobile?
Please let's think about dropdowns or others...
For Year (Mining hardware production standard) dropdown would work.
For the countries also, I think. Tbd: What intervals in % (if any)could be acceptable?
Also: should we work here with landscape view on tap as well as we could with the CO2 graph...?
![dropdowns](https://user-images.githubusercontent.com/50578542/57623920-1b493100-7591-11e9-9e6b-1272d4c65c50.png)

**Comment by kats4** [comment]
Discussion moved into direction of different sliders as a solution. For each country pool separate slider. Have a validation to reach 100%.
For Mining hardware production standard: Dropdown for year should be ok.

**Comment by ikeedo** [comment]
Closing this issue collection, since most issues are done and the remaining were moved to dedicated issues
