### ISSUE TITLE
Sample Data copy/paste Links for better Usability

### ISSUE THREAD

**Issue by kats4** [carbonara-coinpensator/carbonara-frontend#18]
Desktop and Mobile
**Insert shortcut "copy to entry field" below example data**
It is rather cumbersome (especially on mobile...) to copy and past the example data in the calculator into the entry field below.
Idea: Offer a link below each sample data "Copy to entry field" as a shortcut for the user.
![Copytoentry_links](https://user-images.githubusercontent.com/50578542/57621928-e0dd9500-758c-11e9-9e29-5e7f9f697e38.png)

**Comment by VirginiaBalseiro-Zuehlke** [comment]
I fixed them by copying the contents into the input box when clicked on: 

![image](https://user-images.githubusercontent.com/50623445/57698670-6da05580-7656-11e9-89af-aa07e6592967.png)

![image](https://user-images.githubusercontent.com/50623445/57698682-74c76380-7656-11e9-91d1-9a220c561a7e.png)

I also fixed the overlapping by breaking the lines:

![image](https://user-images.githubusercontent.com/50623445/57698713-84df4300-7656-11e9-8766-e00fc7c13834.png)

But as discussed someone else already fixed I think.

**Comment by kats4** [comment]
Thank you, @VirginiaBalseiro-Zuehlke Virginia!
As discussed, I like the solution with the fill in on click.
It would be cool, if the user had the "clear entry field" option as well (e.g. cross or reset).

**Comment by VirginiaBalseiro-Zuehlke** [comment]
I just finished the "reset form x button". Finishing the styling atm.

**Comment by VirginiaBalseiro-Zuehlke** [comment]
This is what it's looking like at the moment: 

![image](https://user-images.githubusercontent.com/50623445/57758847-ea840b80-76f8-11e9-8317-3e0178204139.png)
