### ISSUE TITLE
Calculator: Multiple transactions should be selectable

### ISSUE THREAD

**Issue by kats4** [carbonara-coinpensator/carbonara-frontend#19]
Desktop AND Mobile
**Make multiple transactions selectable**
When entering the wallet address the transactions appear below. The user can only select the transactions one by one for the calculation. 
Idea: Have a column with e.g. Check box so the user can add as many transactions as he wants.
![Select_Transactions](https://user-images.githubusercontent.com/50578542/57702367-35047a00-765e-11e9-95f2-6a4b33416239.png)

**Comment by ikeedo** [comment]
Multiple transactions is now implemented in a feature branch. As soon as the backend api reaches stability on this issue, we can merge the feature. Thank you for the great suggestions, @kats4 !
