### ISSUE TITLE
Optimize User Flow with compensation partners

### ISSUE THREAD

**Issue by kats4** [carbonara-coinpensator/carbonara-frontend#20]
Desktop and Mobile
**Optimize User Flow**
When the user clicks on the compensation Icons of the partners, their pages load in a new tab. But the data of the calculation, the results, are not transferred to the partner widgets. In one case the user has no idea, where to find the widget to calculate compensation at all.
Idea: Some kind of handover of data...?
![Handover_Data](https://user-images.githubusercontent.com/50578542/57702543-97f61100-765e-11e9-894c-24c74f173b75.png)
![Not a clue](https://user-images.githubusercontent.com/50578542/57702580-a6442d00-765e-11e9-81b7-7eee680f03e9.png)

**Comment by kats4** [comment]
Discussion ongoing with partners

**Comment by unibright** [comment]
These are the deep links provided by Naturefund:
https://www.naturefund.de/projekte/kompensation/?kgco2=123 (German)

https://www.naturefund.de/en/projects/compensation/?kgco2=123 (English)

where 123 stands for the CO2 amount to compensate (in kg)

**Comment by unibright** [comment]
Please have in mind, that small amounts of kg will not lead to any "compensation tree". So issue #19 is even more important to have a meaningful compensation proposal.
