### ISSUE TITLE
Avoid too big gaps in longscroller

### ISSUE THREAD

**Issue by kats4** [carbonara-coinpensator/carbonara-frontend#24]
Mobile iPhone
**Avoid too big gaps in longscroller**
The gap between logos and jump marks seems rather big...
![gap](https://user-images.githubusercontent.com/50578542/57623041-3155f200-758f-11e9-9cb4-8a7e4377665b.png)

_Originally posted by @kats4 in https://github.com/carbonara-coinpensator/carbonara-frontend/issues/17#issuecomment-491810863_

**Comment by VirginiaBalseiro-Zuehlke** [comment]
This looks like it was fixed by enlarging the compensation links:

![image](https://user-images.githubusercontent.com/50623445/58090986-ca58be80-7bc8-11e9-8a57-a058dc405514.png)
