### ISSUE TITLE
DESKTOP ONLY: Make interaction icons for CO2 graph bigger

### ISSUE THREAD

**Issue by kats4** [carbonara-coinpensator/carbonara-frontend#31]
Desktop
**Make interaction icons BIGGER**
The icons to zoom in and to reset the zoom on the graph are rather small. 
Idea: Make them bigger, find a more prominent position for them?
Also: in the hover state, a tooltip appears. Here we could add a few more words to make the interaction clearer to the user.
e.g. Magnifier: Select a section to zoom in
Home: Reset zoom (ok)
![Icons-Graph](https://user-images.githubusercontent.com/50578542/57693485-9a9a3b80-7649-11e9-9326-b539763f3a13.png)
![Tooltip](https://user-images.githubusercontent.com/50578542/57693490-a0901c80-7649-11e9-9507-69f8ef7988da.png)

_Originally posted by @kats4 in https://github.com/carbonara-coinpensator/carbonara-frontend/issues/14#issuecomment-492193370_

**Comment by VirginiaBalseiro-Zuehlke** [comment]
I made them bigger. Is this size alright?
However the buttons aren't working (not in the live version either).
![image](https://user-images.githubusercontent.com/50623445/57928162-447b0180-78b0-11e9-8b04-57d29a061c90.png)

**Comment by VirginiaBalseiro-Zuehlke** [comment]
These are my notes so far:
Just making the icons bigger with a CSS rule and media queries works, but not consistently (on certain screen sizes they cannot be clicked on).
The icons can be custom icons, so we could use our own icons which are bigger than the ones that Apexcharts gives us out of the box, but this would be for all screen sizes and not just desktop.
