### ISSUE TITLE
Re-think interaction elements on mobile device for World Map

### ISSUE THREAD

**Issue by kats4** [carbonara-coinpensator/carbonara-frontend#33]
Mobile iPhone
**Rethink interaction elements on mobile**
To be discussed: Are sliders the best interaction elements on mobile?
Please let's think about dropdowns or others...
For Year (Mining hardware production standard) dropdown would work.
For the countries also, I think. Tbd: What intervals in % (if any)could be acceptable?
Also: should we work here with landscape view on tap as well as we could with the CO2 graph...?

![dropdowns](https://user-images.githubusercontent.com/50578542/57623920-1b493100-7591-11e9-9e6b-1272d4c65c50.png)

_Originally posted by @kats4 in https://github.com/carbonara-coinpensator/carbonara-frontend/issues/15#issuecomment-491815347_

**Comment by kats4** [comment]
Discussion moved into direction of different sliders as a solution. For each country pool separate slider. Have a validation to reach 100%.
For Mining hardware production standard: Dropdown for year should be ok.

**Comment by ikeedo** [comment]
We have implemented separate sliders for each country pool. Year selection is done via horizontal slider, which integrates better into overall user experience, especially on mobile devices.
