### ISSUE TITLE
Add disclaimer tooltip messages

### ISSUE THREAD

**Issue by ikeedo** [carbonara-coinpensator/carbonara-frontend#4]

**Comment by kats4** [comment]
@ikeedo Hi Ike, could you specify the issue?

**Comment by ikeedo** [comment]
In order to be transparent about our approach, we want to inform users about the fact that calculations are approximations based on several assumptions, thus the underlying data and calculation results are only approximations and could change as we gather more information.

We want to add short messages at different positions, which can optionally be shown/hidden by users. For example, these could be question marks with tooltip messages or something similar. The messages and their positions still have to be discussed and are not yet defined. 

Technically, this can easily be done with the [Tooltip Component](https://getuikit.com/docs/tooltip) of the embedded UIkit Framework. For mobile, perhaps the [Switcher](https://getuikit.com/docs/switcher) and [Modal](https://getuikit.com/docs/modal) components are better suited.

**Comment by VirginiaBalseiro-Zuehlke** [comment]
> The messages and their positions still have to be discussed and are not yet defined.
Is it necessary to detail the assumptions or could it say something general like in the comment above, "calculations are based on several assumptions, thus the underlying data and calculation results are only approximations and could change as we gather more information"? The position could be next to both calculation results and the message could be the same for both. 
When this is defined I can take this issue.

**Comment by ikeedo** [comment]
Good point! It is a good idea to display the general comment for now as your proposal. Having this tooltip will boost the discussion and we can eventually specialize and add more tooltips in the future. Thank you!
